## Objectives of our projects
1. Perform Exploratory Data Analysis (EDA) to identify patterns, trends, and correlations
among academic factors and placement outcomes.
2. Preprocess and clean the dataset by handling missing values, duplicates, and scaling
features for robust analysis.
3. Build and evaluate multiple machine learning models (Logistic Regression, Decision
Tree) for placement prediction.
4. Compare model performance using metrics such as Accuracy, Precision, Recall, F1-
score, and ROC-AUC.
5. Determine the most influential factors (e.g., CGPA) affecting placement success.
6. Provide actionable insights for students and institutions to enhance placement
preparation and decision-making

In [1]:
#importing nessasary libraries
import pandas as pd
import numpy as np

In [2]:
# importing dataset
df = pd.read_csv("../dataset/college_student_placement_dataset.csv")

In [3]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No

In [4]:
#check diamention
df.shape

(10000, 10)

In [5]:
# Check column names and datatypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   College_ID              10000 non-null  object
 1   IQ                      10000 non-null  int64
 2   Prev_Sem_Result         10000 non-null  float64
 3   CGPA                    10000 non-null  float64
 4   Academic_Performance    10000 non-null  int64
 5   Internship_Experience   10000 non-null  object
 6   Extra_Curricular_Score  10000 non-null  int64
 7   Communication_Skills    10000 non-null  int64
 8   Projects_Completed      10000 non-null  int64
 9   Placement               10000 non-null  object
dtypes: float64(2), int64(5), object(3)
memory usage: 781.4+ KB

## Data Cleaning

### Handle missing values

In [6]:
df.isna().sum()

College_ID                0
IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [7]:
# Observation :- In this dataset their is no any missing value present.

### Handle duplicates

In [8]:
df[df.duplicated()]

Empty DataFrame
Columns: [College_ID, IQ, Prev_Sem_Result, CGPA, Academic_Performance, Internship_Experience, Extra_Curricular_Score, Communication_Skills, Projects_Completed, Placement]
Index: []

Conclusion:- This data is not containing any missing values as well as any duplicate value. It is ready to future process.

In [9]:
# Drop identifier column
df.drop('College_ID',axis = 1,inplace=True)

In [10]:
# Generate summary statistics
# numberic value 
df.describe()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [11]:
# object value
df.describe(include='object')

       Internship_Experience Placement
count                  10000     10000
unique                     2         2
top                       No        No
freq                    6036      8341

In [12]:
(df['CGPA']>10).sum()/len(df)

np.float64(0.0249)

In [13]:
df =df[df["CGPA"]<=10]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9751 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   IQ                      9751 non-null   int64
 1   Prev_Sem_Result         9751 non-null   float64
 2   CGPA                    9751 non-null   float64
 3   Academic_Performance    9751 non-null   int64
 4   Internship_Experience   9751 non-null   object
 5   Extra_Curricular_Score  9751 non-null   int64
 6   Communication_Skills    9751 non-null   int64
 7   Projects_Completed      9751 non-null   int64
 8   Placement               9751 non-null   object
dtypes: float64(2), int64(5), object(2)
memory usage: 761.8+ KB

In [15]:
df.to_csv("../dataset/cleaned_data.csv",index=False)